apiVersion: v2
name: app
description: A Helm chart for Kubernetes Deployment
type: application

version: 0.18.0

keywords:
  - deployment
  - StatefulSet
  - configmap
  - secret
  - HorizontalPodAutoscaler
  - hpa
  - VerticalPodAutoscaler
  - podDisruptionBudget
  - service
  - ingress
  - gateway
  - httproute
  - grpcroute
  - analysisTemplate
  - rbac

maintainers:
  - name: juri
    url: https://github.com/juriku/helm-charts

dependencies:
  - name: base
    version: ~0
    repository: file://../base