apiVersion: v2
name: argo-applications
description: A Helm chart for Kubernetes argo applications
type: application

version: 0.17.2

keywords:
  - argocd
  - workflows

maintainers:
  - name: juri
    url: https://github.com/juriku/helm-charts