{{ include "base.configmaps" . }}
{{ include "base.secrets" . }}
{{ include "base.service" . }}
{{ include "base.ingress" . }}
{{ include "base.gateway" . }}
{{ include "base.httproute" . }}
{{ include "base.grpcroute" . }}
{{ include "base.verticalPodAutoscaler" . }}
{{ include "base.podDisruptionBudget" . }}
{{ include "base.horizontalPodAutoscaler" . }}
{{ include "base.keda" . }}
{{ include "base.PriorityClass" . }}
{{ include "base.rbac" . }}
{{ include "base.deployment" . }}
{{ include "base.statefulSet" . }}
{{ include "base.argoRollouts" . }}
{{ include "base.argoRolloutsNative" . }}
{{ include "base.analysisTemplate" . }}
{{ include "base.pvc" . }}
{{ include "base.raw" . }}