{{ include "base.configmaps" . }}
{{ include "base.secrets" . }}
{{ include "base.service" . }}
{{ include "base.ingress" . }}
{{ include "base.verticalPodAutoscaler" . }}
{{ include "base.podDisruptionBudget" . }}
{{ include "base.horizontalPodAutoscaler" . }}
{{ include "base.deployment" . }}